title: Wenzhi Ding (Dave) | Personal Website
title_zh: 丁文治 | 个人网站
email: wenzhi.ding@connect.hku.hk
description: >- # this means to ignore newlines until "baseurl:"
  Wenzhi Ding (Dave) is a Ph.D. student at the University of Hong Kong 
  in the finance area. His research interests lie at how law and technology 
  change finance, and further, change business.
description_zh: >-
  丁文治是香港大学金融学系的在读博士生。他主要的研究方向是科技和法律对金融的影响，以及更进一步对商业社会的影响。
url: "https://wding.page" # the base hostname & protocol for your site, e.g. http://example.com
position: "Ph.D. Student @ HKU"

show_excerpts: true

sass:
  sass_dir: _sass

plainwhite:
  name: Wenzhi Ding (Dave)
  name_zh: 丁文治
  tagline: Finance, Tech, Law
  tagline_zh: 金融 | 科技 | 法律
  date_format: "%b %-d, %Y"
  date_format_zh: "%Y年%-m月%-d日"
  dark_mode: true
  sitemap: true
  search: true

  portfolio_image: "assets/portfolio.png"
  html_lang: "en"
  html_lang_cn: "zh-cn"

  condensed_mobile:
    - page
    - post
    - page_zh

  analytics_id: "UA-150104052-1"

  navigation:
    - title: Main
      title_zh: 首页
      url: "/index.html"
      url_zh: "/index_zh.html"
    - title: Research
      title_zh: 学术研究
      url: "/pages/research.html"
      url_zh: "/pages/research_zh.html"
    - title: Project
      title_zh: 个人项目
      url: "/pages/project.html"
      url_zh: "/pages/project_zh.html"
    - title: Teaching
      title_zh: 课程资料
      url: "/pages/teaching.html"
      url_zh: "/pages/teaching_zh.html"

  social_links:
    github: Wenzhi-Ding
    # rss: rss
    ssrn: 3268426

# Build settings
theme: plainwhite
# remote_theme: samarsault/plainwhite-jekyll
plugins:
#  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
