title: Wenzhi Ding | Personal Website
email: wenzhi.ding@connect.hku.hk
description: >- # this means to ignore newlines until "baseurl:"
  Wenzhi Ding (丁文治) is a Ph.D. student at the University of Hong Kong 
  in the finance area. His research interests lie at how law and technology 
  change finance, and further, change business.
url: "https://wding.page" # the base hostname & protocol for your site, e.g. http://example.com
position: "Ph.D. Student @ HKU"

show_excerpts: true

sass:
  sass_dir: _sass

plainwhite:
  name: 丁文治 Wenzhi Ding 
  tagline: Finance, Tech, Law
  date_format: "%b %-d, %Y"
  dark_mode: true
  sitemap: true
  search: true

  portfolio_image: "assets/portfolio.png"
  html_lang: "en"

  condensed_mobile:
    #- home
    - page
    - post
    
  # disqus_shortname: wenzhi_ding

  analytics_id: "UA-150104052-1"

  navigation:
    - title: Research
      url: "/index"
    # - title: Research
    #   url: "/pages/research"
    - title: Project
      url: "/pages/project"
    - title: Teaching
      url: "/pages/teaching"

  social_links:
    # twitter:
    github: Wenzhi-Ding
    # linkedIn:
    rss: rss
    ssrn: 3268426

# Build settings
theme: plainwhite
# remote_theme: samarsault/plainwhite-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
