title: Wenzhi Ding | Main Page
author: Wenzhi Ding
email: wenzhi.ding@connect.hku.hk
description: > # this means to ignore newlines until "show_exerpts:"
  Wenzhi Ding (丁文治) is a Ph.D. student at the University of Hong Kong 
  in the finance area. His research interests lie at finance, technology 
  and legal study.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: 丁文治 Wenzhi Ding 
  tagline: Law, Technology, Finance
  date_format: "%Y-%m-%d %H:%M"
  sitemap: true # set to true to generate sitemap.xml content
  analytics_id: "UA-150104052-1"

  # generate social links in footer
  social_links:
    twitter: daveting1995
    github: Wenzhi-Ding
    linkedIn: in/wenzhi-ding
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed